vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.hlsearch = true
vim.opt.incsearch = false
vim.opt.scrolloff=8
vim.opt.clipboard="unnamed"
vim.opt.smartindent = true
vim.opt.wrap = false 
vim.opt.laststatus=2
vim.opt.backspace = "indent,eol,start"
vim.opt.termguicolors = true
vim.opt.background = 'dark'
-- regex engine
vim.opt.re=0
vim.opt.pumheight=10
vim.opt.mouse="nicr"
vim.opt.colorcolumn="120"
